"""grade table

Revision ID: 574a19cb726d
Revises: ee2e6d6f637c
Create Date: 2019-01-02 21:02:24.757504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574a19cb726d'
down_revision = 'ee2e6d6f637c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('course', sa.String(length=40), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('course')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###
